# Generated by Django 4.1.3 on 2022-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('cuit', models.IntegerField(primary_key=True, serialize=False, verbose_name='CUIT')),
                ('denominacion', models.CharField(max_length=40, verbose_name='Denominación')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('empleador', models.BooleanField(verbose_name='Es Em´ñeador')),
                ('empleado', models.BooleanField(verbose_name='Es Empleado')),
                ('activo', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'ordering': ['-cuit'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cuit', models.IntegerField(primary_key=True, serialize=False, verbose_name='CUIT Empleado')),
                ('cuit_empleador', models.IntegerField(verbose_name='CUIT Empleador')),
                ('legajo', models.CharField(max_length=10, verbose_name='Legajo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('conyuje', models.BooleanField(verbose_name='Conyuje a Cargo')),
                ('hijos', models.IntegerField(verbose_name='Cantidad de Hijos a Cargo')),
            ],
            options={
                'ordering': ['-cuit'],
            },
        ),
    ]
