# Generated by Django 4.1.3 on 2022-12-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyente', '0002_concepto_ingreso_alter_contribuyente_empleador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto_ingreso',
            name='id_concepto',
        ),
        migrations.AddField(
            model_name='concepto_ingreso',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
