# Generated by Django 4.1.3 on 2022-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyente', '0003_remove_concepto_ingreso_id_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='conyuje',
            field=models.BooleanField(verbose_name='Conyuge a Cargo'),
        ),
    ]
